#Spring Boot configuration
server:
  port: 8080
spring:
  profiles:
    active: development
  application:
    name: users-manager
# Connecting to LDAP Server
  ldap:
    urls: "ldap://myserver:1235"
    username: "admin"
    password: "secret"

#Database config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbname
    username: postgres
    password: 16180
# JPA properties
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true